apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: my-collector
spec:
  mode: statefulset
  replicas: 3
  priorityClassName: system-node-critical
  envs:
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
  config:
    extensions:
      health_check:
        endpoint: "0.0.0.0:13133"
  
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${POD_IP}:4317
          http:
            endpoint: ${POD_IP}:4318
      prometheus:
        config:
          global:
            scrape_interval: 30s
          scrape_configs:
            - job_name: opentelemetry-collector
              static_configs:
                - targets:
                    - ${POD_IP}:8888
  
    service:
      pipelines:
        metrics:
          receivers: [otlp, prometheus]
          exporters: [logging] 
        traces:
          receivers: [otlp] 
          exporters: [logging]
      extensions: [health_check]
