apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otel

helmCharts:
- name: opentelemetry-collector
  repo: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.66.4
  releaseName: opentelemetry-collector
  valuesFile: values.yaml
  includeCRDs: true
