apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmCharts:
- name: opentelemetry-operator
  repo: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.69.0
  releaseName: opentelemetry-collector
  valuesFile: values.yaml
  includeCRDs: true

resources:
  - collector.yaml
