manager:
  collectorImage:
    repository: "otel/opentelemetry-collector-k8s"
  resources:
    limits:
      cpu: null
      memory: null
    requests:
      cpu: null
      memory: null

  prometheusRule:
    enabled: true

admissionWebhooks:
  certManager:
    enabled: false
  autoGenerateCert:
    enabled: true
