fullnameOverride: otel-collector
mode: deployment
priorityClassName: system-node-critical
replicaCount: 1

extraEnvs:
  - name: POD_IP
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: status.podIP
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: spec.nodeName

config:
  extensions:
    health_check:
      endpoint: "0.0.0.0:13133"
  
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${POD_IP}:4317
        http:
          endpoint: ${POD_IP}:4318
    prometheus:
      config:
        global:
          scrape_interval: 30s
        scrape_configs:
          - job_name: opentelemetry-collector
            static_configs:
              - targets:
                  - ${POD_IP}:8888
    exporters:
    logging:
    otlp:
  
  service:
    pipelines:
      metrics:
        receivers: [otlp, prometheus]
        exporters: [logging] 
      traces:
        receivers: [otlp] 
        exporters: [logging]
    extensions: [health_check]

ports:
  otlp:
    enabled: true
  otlp-http:
    enabled: true
  metrics:
    enabled: true
