apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: grafana
    repo: https://fluent.github.io/helm-charts
    version: 6.55.0
    releaseName: fluentd
    namespace: monitoring
    valuesFile: values.yaml
