apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 1password

helmCharts:
- name: connect
  version: 1.16.0
  repo: https://1password.github.io/connect-helm-charts
  releaseName: connect
  valuesFile: values.yaml
