apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-client-envoy
  namespace: gateway
  labels:
    app.kubernetes.io/name: dex
    app.kubernetes.io/component: static-client-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: dex-client-envoy
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: dex-client-envoy
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: dex-client-envoy
        property: client-secret
