apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops

helmCharts:
  - name: kuberay-operator
    repo: https://ray-project.github.io/kuberay-helm/
    version: 1.1.1
    releaseName: kuberay-operator
    includeCRDs: true
    valuesFile: values.yaml
