apiVersion: v1
kind: Secret
metadata:
  name: 1password-credentials
data:
# cat 1password-credentials.json | base64 | \  tr '/+' '_-' | tr -d '=' | tr -d '\n' > FILE_NAME
  credentials.json: 
---
apiVersion: v1
kind: Secret
metadata:
  name: 1password-token
data:
# op connect token create op-k8s-operator --server SERVER --vault VAULT
  token: 
