apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quanianitis.in-cluster.system.external-secrets
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: external-secrets
    server: https://kubernetes.default.svc
  source:
    path: infra/kustomize/external-secrets
    repoURL: https://github.com/ian-chan-ml/homelab
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true

