apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: external-secrets
    chart: external-secrets/external-secrets
    version: v0.10.3
    repo: https://charts.external-secrets.io
    releaseName: external-secrets
    includeCRDs: true

namspace: kube-system
