apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: argocd-repo-server
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  itemPath: "vaults/quanianitis.com/items/argocd-app-repo-server"
