fullnameOverride: argocd
dex:
  enabled: false
notifications:
  enabled: false
applicationSet:
  enabled: true
configs:
  params:
    server.insecure: true
  cm:
    kustomize.buildOptions: --enable-alpha-plugins --enable-helm --enable-exec
