apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: connect
  version: 1.15.0
  repo: https://1password.github.io/connect-helm-charts
  releaseName: 1password
  valuesFile: values.yaml

resources:
  - secrets.yaml
